name: code build test

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout code
            uses: actions/checkout@v2
        
        -   name: Setup go environment
            uses: actions/setup-go@v2

        -   name: Test libdownloader
            run: cd gosci-hub/libdownloader && go test -v
        
        -   name: Test libgoscihub
            run: cd gosci-hub/libgoscihub && go test -v
        
        -   name: Compile project
            run: cd gosci-hub/ && go build
